// flow-typed signature: 3232a3600c64b511e1ca1b15d7956970
// flow-typed version: <<STUB>>/async-reactor_v^1.2.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'async-reactor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'async-reactor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'async-reactor/lib/element' {
  declare module.exports: any;
}

declare module 'async-reactor/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'async-reactor/lib/element.js' {
  declare module.exports: $Exports<'async-reactor/lib/element'>;
}
declare module 'async-reactor/lib/index.js' {
  declare module.exports: $Exports<'async-reactor/lib/index'>;
}
