// flow-typed signature: 180e5c61ea51f04d4b1fbe1ec39613b7
// flow-typed version: <<STUB>>/babel-flow-webpack-plugin_v1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-flow-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-flow-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-flow-webpack-plugin/index' {
  declare module.exports: $Exports<'babel-flow-webpack-plugin'>;
}
declare module 'babel-flow-webpack-plugin/index.js' {
  declare module.exports: $Exports<'babel-flow-webpack-plugin'>;
}
