// flow-typed signature: b1b3360c8182d498fa7390e8f7231d26
// flow-typed version: <<STUB>>/postscribe_v^2.0.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postscribe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postscribe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postscribe/dist/postscribe' {
  declare module.exports: any;
}

declare module 'postscribe/dist/postscribe.max' {
  declare module.exports: any;
}

declare module 'postscribe/dist/postscribe.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postscribe/dist/postscribe.js' {
  declare module.exports: $Exports<'postscribe/dist/postscribe'>;
}
declare module 'postscribe/dist/postscribe.max.js' {
  declare module.exports: $Exports<'postscribe/dist/postscribe.max'>;
}
declare module 'postscribe/dist/postscribe.min.js' {
  declare module.exports: $Exports<'postscribe/dist/postscribe.min'>;
}
