// flow-typed signature: 129c7287a19a87e0bc8a3845cc7eb3bb
// flow-typed version: <<STUB>>/postcss-custom-properties_v^6.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-custom-properties/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-custom-properties/dist/index.js' {
  declare module.exports: $Exports<'postcss-custom-properties/dist/index'>;
}
