// flow-typed signature: 82c59f0f2e436a85e25dc19ca6839408
// flow-typed version: <<STUB>>/react-scroll-to_v^2.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scroll-to'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scroll-to' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scroll-to/config/webpack.config' {
  declare module.exports: any;
}

declare module 'react-scroll-to/dist/react-scroll-to' {
  declare module.exports: any;
}

declare module 'react-scroll-to/docs/static/iframe.6cc71ada6d24d09cf9ad.bundle' {
  declare module.exports: any;
}

declare module 'react-scroll-to/docs/static/manager.08c9b945bba98c15a6a7.bundle' {
  declare module.exports: any;
}

declare module 'react-scroll-to/docs/static/runtime~iframe.36305751f78a2d599ec4.bundle' {
  declare module.exports: any;
}

declare module 'react-scroll-to/docs/static/runtime~manager.9ffd8dd7b8642e4235e2.bundle' {
  declare module.exports: any;
}

declare module 'react-scroll-to/docs/static/vendors~iframe.64825ef69626ef9c8f63.bundle' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/index' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/ScrollArea' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/ScrollTo' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/ScrollToHOC' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/tests/generateId.spec' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/tests/ScrollArea.spec' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/tests/ScrollTo.spec' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/tests/ScrollToHOC.spec' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/tests/setup/setupTests' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/tests/setup/shim' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/utilities/generateId' {
  declare module.exports: any;
}

declare module 'react-scroll-to/src/utilities/getDisplayName' {
  declare module.exports: any;
}

declare module 'react-scroll-to/stories/Default' {
  declare module.exports: any;
}

declare module 'react-scroll-to/stories/HigherOrderComponent' {
  declare module.exports: any;
}

declare module 'react-scroll-to/stories/index' {
  declare module.exports: any;
}

declare module 'react-scroll-to/stories/ScrollByRef' {
  declare module.exports: any;
}

declare module 'react-scroll-to/stories/WithScrollArea' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scroll-to/config/webpack.config.js' {
  declare module.exports: $Exports<'react-scroll-to/config/webpack.config'>;
}
declare module 'react-scroll-to/dist/react-scroll-to.js' {
  declare module.exports: $Exports<'react-scroll-to/dist/react-scroll-to'>;
}
declare module 'react-scroll-to/docs/static/iframe.6cc71ada6d24d09cf9ad.bundle.js' {
  declare module.exports: $Exports<'react-scroll-to/docs/static/iframe.6cc71ada6d24d09cf9ad.bundle'>;
}
declare module 'react-scroll-to/docs/static/manager.08c9b945bba98c15a6a7.bundle.js' {
  declare module.exports: $Exports<'react-scroll-to/docs/static/manager.08c9b945bba98c15a6a7.bundle'>;
}
declare module 'react-scroll-to/docs/static/runtime~iframe.36305751f78a2d599ec4.bundle.js' {
  declare module.exports: $Exports<'react-scroll-to/docs/static/runtime~iframe.36305751f78a2d599ec4.bundle'>;
}
declare module 'react-scroll-to/docs/static/runtime~manager.9ffd8dd7b8642e4235e2.bundle.js' {
  declare module.exports: $Exports<'react-scroll-to/docs/static/runtime~manager.9ffd8dd7b8642e4235e2.bundle'>;
}
declare module 'react-scroll-to/docs/static/vendors~iframe.64825ef69626ef9c8f63.bundle.js' {
  declare module.exports: $Exports<'react-scroll-to/docs/static/vendors~iframe.64825ef69626ef9c8f63.bundle'>;
}
declare module 'react-scroll-to/src/index.js' {
  declare module.exports: $Exports<'react-scroll-to/src/index'>;
}
declare module 'react-scroll-to/src/ScrollArea.jsx' {
  declare module.exports: $Exports<'react-scroll-to/src/ScrollArea'>;
}
declare module 'react-scroll-to/src/ScrollTo.jsx' {
  declare module.exports: $Exports<'react-scroll-to/src/ScrollTo'>;
}
declare module 'react-scroll-to/src/ScrollToHOC.jsx' {
  declare module.exports: $Exports<'react-scroll-to/src/ScrollToHOC'>;
}
declare module 'react-scroll-to/src/tests/generateId.spec.js' {
  declare module.exports: $Exports<'react-scroll-to/src/tests/generateId.spec'>;
}
declare module 'react-scroll-to/src/tests/ScrollArea.spec.jsx' {
  declare module.exports: $Exports<'react-scroll-to/src/tests/ScrollArea.spec'>;
}
declare module 'react-scroll-to/src/tests/ScrollTo.spec.jsx' {
  declare module.exports: $Exports<'react-scroll-to/src/tests/ScrollTo.spec'>;
}
declare module 'react-scroll-to/src/tests/ScrollToHOC.spec.jsx' {
  declare module.exports: $Exports<'react-scroll-to/src/tests/ScrollToHOC.spec'>;
}
declare module 'react-scroll-to/src/tests/setup/setupTests.js' {
  declare module.exports: $Exports<'react-scroll-to/src/tests/setup/setupTests'>;
}
declare module 'react-scroll-to/src/tests/setup/shim.js' {
  declare module.exports: $Exports<'react-scroll-to/src/tests/setup/shim'>;
}
declare module 'react-scroll-to/src/utilities/generateId.js' {
  declare module.exports: $Exports<'react-scroll-to/src/utilities/generateId'>;
}
declare module 'react-scroll-to/src/utilities/getDisplayName.js' {
  declare module.exports: $Exports<'react-scroll-to/src/utilities/getDisplayName'>;
}
declare module 'react-scroll-to/stories/Default.jsx' {
  declare module.exports: $Exports<'react-scroll-to/stories/Default'>;
}
declare module 'react-scroll-to/stories/HigherOrderComponent.jsx' {
  declare module.exports: $Exports<'react-scroll-to/stories/HigherOrderComponent'>;
}
declare module 'react-scroll-to/stories/index.jsx' {
  declare module.exports: $Exports<'react-scroll-to/stories/index'>;
}
declare module 'react-scroll-to/stories/ScrollByRef.jsx' {
  declare module.exports: $Exports<'react-scroll-to/stories/ScrollByRef'>;
}
declare module 'react-scroll-to/stories/WithScrollArea.jsx' {
  declare module.exports: $Exports<'react-scroll-to/stories/WithScrollArea'>;
}
