/**
 * Flowtype definitions for index
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.3.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

export type ChartDataFunction<T> = (element: HTMLElement) => T;
export type ChartData<T> = ChartDataFunction<T> | T;
export interface ChartComponentProps {
  data: ChartData<chartjs.ChartData>;
  type?: chartjs.ChartType;
  getDatasetAtEvent(e: any): void;
  getElementAtEvent(e: any): void;
  getElementsAtEvent(e: any): void;
  height?: number;
  legend?: chartjs.ChartLegendOptions;
  onElementsClick(e: any): void;
  options?: chartjs.ChartOptions;
  plugins?: "NO PRINT IMPLEMENTED: ObjectKeyword"[];
  redraw?: boolean;
  width?: number;
  datasetKeyProvider?: (any: any) => any;
}
export type LinearComponentProps = {
  data: ChartData<chartjs.ChartData>
} & ChartComponentProps;
declare export default class ChartComponent<P> mixins React.Component<P, {}> {
  chartInstance: chartjs;
}
declare export class Doughnut mixins ChartComponent<ChartComponentProps> {}
declare export class Pie mixins ChartComponent<ChartComponentProps> {}
declare export class Line mixins ChartComponent<LinearComponentProps> {}
declare export class Scatter mixins ChartComponent<ChartComponentProps> {}
declare export class Bar mixins ChartComponent<LinearComponentProps> {}
declare export class HorizontalBar mixins ChartComponent<ChartComponentProps> {}
declare export class Radar mixins ChartComponent<ChartComponentProps> {}
declare export class Polar mixins ChartComponent<ChartComponentProps> {}
declare export class Bubble mixins ChartComponent<ChartComponentProps> {}
declare export var defaults: {};
